<style>
</style>
<script src="https://cdnjs.cloudflare.com/ajax/libs/zxcvbn/4.4.1/zxcvbn.js"></script>

<form method="post" action="<?= $this->url('auth-change-password') ?>" class="auth">

    <label for="password">Current Password:</label>
    <input type="password" name="password" id="current-password" placeholder="Current Password"><br>

    <label for="new-password">New Password:</label>
    <input type="password" name="newPassword" id="new-password" placeholder="New Password"><br>
    <input type="checkbox" id="show-pass"><br>

    <input type="hidden" name="__csrf_value" value="<?= $this->csrfToken() ?>">

    <input type="submit" value="Change Password">
    <pre id="console"></pre>

</form>

<script>
//Place this plugin snippet into another file in your applicationb

//Here how to call above plugin from everywhere in your application document body
$.toggleShowPassword({
    field: '#new-password',
    control: '#show-pass'
});
$(document).ready(function() {
    result = zxcvbn('');
    $("#new-password").keyup(function() {
        result = zxcvbn($('#new-password').val());
        $('#console').text(JSON.stringify(result, null, '\t'));
    });

});
</script>
